#+TITLE: Org file for dotfiles
#+AUTHOR: Anishka Patel
#+DESCRIPTION: A detailed explanation for creation and usage of my dotfiles.
#+EMAIL: anishka.vpatel@gmail.com
#+DATE: [2022-08-25 Thu]
#+OPTIONS: toc:2

* Bash Config
Click below to take a look:
[[file:.bashrc][.bashrc file]]

Generated by the code below:
#+BEGIN_SRC bash
ln ~/.bashrc
#+END_SRC

* Zsh Config
Click below to take a look:
[[file:.zshrc][.zshrc file]]

Generated by the code below:
#+BEGIN_SRC bash
ln ~/.zshrc
#+END_SRC
* Vim Config
Click below to take a look:
[[file:.vimrc][.vimrc file]]

Generate by the code below:
#+BEGIN_SRC bash
ln ~/.vimrc
#+END_SRC
** Requirements
- Vim
#+begin_src bash
sudo pacman -S vim
#+end_src
* AstroNvim config
AstroNvim - Another more advanced distribution for neovim with IDE like features.
** Requirements
- Neovim 0.7+
#+begin_src bash
sudo pacman -S neovim --noconfirm
#+end_src
- Nerd Fonts
#+begin_src bash
sudo yay -S nerd-fonts-complete
#+end_src
- Terminal w/ true color
#+begin_src bash
sudo pacman -S kitty --noconfirm
#+end_src
- Optional:
#+begin_src bash
sudo pacman -S ripgrep lazygit ncdu htop python nodejs --noconfirm
#+end_src
** Install - [[https://github.com/AstroNvim/AstroNvim][GitHub - AstroNvim]]
#+BEGIN_SRC bash
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim +PackerSync
#+END_SRC
** Docs Link - [[https://astronvim.github.io/][Getting Started | AstroNvim]]
** Notes
- AstroNvim(nvim) does remove previous nvim configurations.
- nvim binary located at ~"/usr/bin/nvim"~
- Plugins are added to ~plugin~ section in ~"~/.config/nvim/lua/user/init.lua"~
- Some plugins require modifying ~init.lua~ file at ~"~/.config/nvim/init.lua"~
- Imp commands
  - ~:LspInstall~
  - ~:TSInstall~
  - ~:PackerSync~
  - ~:AstroUpdate~
- Personal modifications outside ~user/init.lua~
  - Show menu name in neovim completions
     ~ ~/.config/nvim/lua/configs/cmp.lua~
#+begin_src lua
-- format = function(_, vim_item) -- removed
format = function(entry, vim_item) -- modified
  vim_item.kind = string.format("%s", kind_icons[vim_item.kind]) -- nop
  vim_item.menu = ({      -- added
      luasnip = "[SNIP]", -- added
      nvim_lsp = "[LSP]", -- added
      buffer = "[BUFF]",  -- added
      path = "[PATH]",    -- added
  })[entry.source.name]   -- added
  return vim_item -- nop
#+end_src

* DoomEmacs config
** Requirements
** Install
** Notes
* Gesture config
Configuration for ~Gestures~ Application.
~Gestures~ application binds various keyboard shortcuts to touchpad gestures.
** Install ~Gestures~ application
#+BEGIN_SRC bash
sudo pacman -Syu community/gestures
#+END_SRC
** Configuration
Files stored as ~"~/.config/libinput-gestures.conf"~
Link to file: [[file:.config/libinput-gestures.conf][Gestures config file.]]

* Pacman packages
Pacman: Package installer for Arch Linux
** List generated
1. Explicitly installed packages
   Link to file: [[file:pacman-packages-list.txt][Pacman-Packages-List]]
   Created with command:
#+BEGIN_SRC bash
pacman -Qqe > pacman-packages-list.txt
#+END_SRC
2. All packages
   Link to file: [[file:pacman-packages-list-full.txt][Pacman-Full-Packages-List]]
   Created with command:
#+BEGIN_SRC bash
pacman -Qq > pacman-packages-list-full.txt
#+END_SRC
3. Pacman option to remember for list generation:
   |--------+-----------------------------------------|
   | Option | Action                                  |
   |--------+-----------------------------------------|
   | -Q     | List all packages with version          |
   | -q     | List all packages without version       |
   | -e     | List all explicitly installed packages  |
   | -n     | List packages omitting foreign packages |
   | -m     | List all foreign packages               |
   |--------+-----------------------------------------|
4. Examples
#+BEGIN_SRC bash
pacman -Qqen
#+END_SRC
5. Link for reference: [[https://wiki.archlinux.org/title/pacman/Tips_and_tricks#List_of_installed_packages][Pacman/Tips and tricks - ArchWiki]]
* Pip global packages
Pip: Package install for python
Link to file: [[file:pip-packages-list.txt][pip-packages-list]]
#+BEGIN_SRC bash
pip freeze | awk '{print $1}' > pip-packages-list.txt
#+END_SRC
* Npm global packages
Npm: Node package manager
Link to file: [[file:npm-packages-list.txt][npm-packages-list]]
 #+BEGIN_SRC bash
 npm -g list | awk '{print $2}' | awk -F '@' '{print $1}' > npm-packages-list.txt
 #+END_SRC

#  LocalWords:  Pacman Npm Zsh AstroNvim neovim
