#+TITLE: Org file for dotfiles
#+AUTHOR: Anishka Patel
#+DESCRIPTION: A detailed explanation for creation and usage of my dotfiles.
#+EMAIL: anishka.vpatel@gmail.com
#+DATE: [2022-08-25 Thu]
#+OPTIONS: toc:3
#+auto_tangle: t

* Project Structure
Directory structure for whole repository.
#+begin_src bash :shebang /usr/bin/bash :results code :exports both
tree . -L 1 -a -d
#+end_src

#+RESULTS:
#+begin_src bash
.
├── .config
├── .doom.d
├── exports
├── .git
├── install-script
├── .local
├── manuals
└── packages-list

8 directories
#+end_src
Files in the current directory
#+begin_src bash :shebang /usr/bin/bash :results code :exports both
tree . -L 1 -a -F |  grep -v /$
#+end_src

#+RESULTS:
#+begin_src bash
├── .bashrc
├── dotconfig.sh
├── .exrc
├── .gitignore
├── README.md
├── README.org
├── script.sh*
├── .vimrc
└── .zshrc

8 directories, 9 files
#+end_src

** Setup dotconfig.sh
#+begin_src bash :tangle dotconfig.sh
#!/usr/bin/bash
# Title: Dotconfig Script
# Description: A script file to copy relevant files to relevent directories and backup where it is required
# Created: [2022-09-16 Fri]
# Usage: ./dotconfig.sh

errorCheck () {
    if [[ $? -eq 0 ]]; then
        echo "Completed"
    else
        echo "Error"
    fi
}
#+end_src

** Setup dotupdate.sh
#+begin_src bash :tangle dotupdate.sh
#!/usr/bin/bash
# Title: Dotupdate script
# Description: A script to update releant files to relevant directories
# Created: [2022-10-31 Mon]
# Usage: ./dotupdate.sh

errorCheck () {
    if [[ $? -eq 0 ]]; then
        echo "Completed"
    else
        echo "Error"
    fi
}
#+end_src

** Dotconfig file
File to quick setup links to appropriate directories
Link to file: [[file:dotconfig.sh][dotconfig.sh]]
* Shells
#+begin_src bash :results code :exports both
cat /etc/shells
#+end_src

#+RESULTS:
#+begin_src bash
# Pathnames of valid login shells.
# See shells(5) for details.

/bin/sh
/bin/bash
/bin/zsh
/usr/bin/zsh
/usr/bin/git-shell
/usr/bin/fish
/bin/fish
#+end_src

** Bash Config
Click below to take a look:
[[file:.bashrc][.bashrc file]]

Generated by hard linking. The code is below:
#+BEGIN_SRC bash :tangle dotupdate.sh
echo -n "Updating .bashrc file..."
cp ~/.bashrc .
errorCheck
#+END_SRC
***  Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.bashrc ]]; then
    echo -n "Backing up old .bashrc file..."
    mv ~/.bashrc ~/.bashrc.bak
    errorCheck
fi
echo -n "Setting up bash files..."
cp .bashrc ~
errorCheck
#+end_src
** Zsh Config
Click below to take a look:
[[file:.zshrc][.zshrc file]]

Generated by hard linking. The code is below:
#+BEGIN_SRC bash :tangle dotupdate.sh
echo -n "Updating .zshrc file..."
cp ~/.zshrc .
errorCheck
#+END_SRC
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.zshrc ]]; then
    echo -n "Backing up old .zshrc file..."
    mv ~/.zshrc ~/.zshrc.bak
    errorCheck
fi
echo -n "Setting up zsh files..."
cp .zshrc ~
errorCheck
#+end_src
** Fish config
Click below to take a look:
[[file:.config/fish/config.fish][config.fish]]

Generated by hard linking. The code is below:
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating fish config file..."
cp  ~/.config/fish/config.fish .config/fish/
errorCheck
#+end_src
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.config/fish/config.fish ]]; then
    echo -n "Backing up old config.fish file..."
    mv ~/.config/fish/config.fish ~/.config/fish/config.fish.bak
    errorCheck
fi
echo -n "Setting up fish config files..."
cp  .config/fish/config.fish ~/.config/fish/
errorCheck
#+end_src
* Terminals
** Kitty
A GPU accelerated totally configurable terminal
*** Install
#+begin_src bash
sudo pacman -S kitty --noconfirm
#+end_src
*** Kitty config
Click below to take a look:
[[file:.config/kitty/kitty.conf][kitty.conf]]
Generated by hard linking. The code is below:
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating kitty config file..."
cp  ~/.config/kitty/kitty.conf .config/kitty/
errorCheck
#+end_src
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.config/kitty/kitty.conf ]]; then
    echo -n "Backing up old kitty.conf file..."
    mv ~/.config/kitty/kitty.conf ~/.config/kitty/kitty.conf.bak
    errorCheck
fi
echo -n "Setting up kitty files..."
cp  .config/kitty/kitty.conf ~/.config/kitty/
errorCheck
#+end_src
** Konsole
Managed through KDE config : [[*KDE-Config][KDE-Config]]
*** Install
#+begin_src bash
sudo pacman -S konsole --noconfirm
#+end_src
** Yakuake
Managed through KDE config : [[*KDE-Config][KDE-Config]]
*** Install
#+begin_src bash
sudo pacman -S yakuake --noconfirm
#+end_src
* Editors
** Vi Config
Click below to take a look:
[[file:.exrc][.exrc file]]

Generated by the code below:
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating vi config files..."
cp ~/.exrc .
errorCheck
#+end_src
*** Requirements
Vi
#+begin_src bash
sudo pacman -S vi --noconfirm
#+end_src
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.exrc ]]; then
    echo -n "Backing up old vim files..."
    mv ~/.exrc ~/.exrc.bak
    errorCheck
fi
echo -n "Setting up vi files..."
cp .exrc ~
errorCheck
#+end_src
** Vim Config
Click below to take a look:
[[file:.vimrc][.vimrc file]]

Generate by the code below:
#+BEGIN_SRC bash :tangle dotupdate.sh
echo -n "Updating vim config files..."
cp ~/.vimrc .
errorCheck
#+END_SRC
*** Requirements
- Vim
#+begin_src bash
sudo pacman -S vim --noconfirm
#+end_src
*** Notes
- Run ~:PlugInstall~ inside vim to install plugins
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.vimrc ]]; then
    echo -n "Backing up old vim files..."
    mv ~/.vimrc ~/.vimrc.bak
    errorCheck
fi
echo -n "Setting up vim files..."
cp .vimrc ~
errorCheck
#+end_src
** Nvim config
*** Requirements
- Neovim 0.7+
#+begin_src bash
sudo pacman -S neovim --noconfirm
#+end_src
*** Update files
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating nvim/init.lua file..."
cp  ~/.config/nvim/init.lua .config/nvim/
errorCheck
echo -n "Updating nvim/lua/user/init.lua file..."
cp  ~/.config/nvim/lua/user/init.lua .config/nvim/lua/user/
errorCheck
#+end_src
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.config/nvim/init.lua ]]; then
    echo -n "Backing up old nvim/init.lua"
    mv ~/.config/nvim/init.lua ~/.config/nvim/init.lua.bak
    errorCheck
fi
echo -n "Setting up nvim/init.lua"
cp  .config/nvim/init.lua ~/.config/nvim/
errorCheck
if [[ -f ~/.config/nvim/lua/user/init.lua ]]; then
    echo -n "Backing up old nvim/lua/user/init.lua"
    mv ~/.config/nvim/lua/user/init.lua ~/.config/nvim/lua/user/init.lua.bak
    errorCheck
fi
echo -n "Setting up nvim/lua/user/init.lua"
cp  .config/nvim/lua/user/init.lua ~/.config/nvim/lua/user/
errorCheck
#+end_src
** LunarVim config
LunarVim - Another pre-configure great out-of-the-box neovim setup
*** Requirements
- NerdFonts
*** Doc Link: [[https://www.lunarvim.org/][LunarVim | Documentation]]
*** Install
#+begin_src bash
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
#+end_src
*** Update files
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating lvim/config.lua file..."
cp  ~/.config/lvim/config.lua .config/lvim/
errorCheck
#+end_src
*** Setup files
#+begin_src bash :tangle dotconfig.sh
if [[ -f ~/.config/lvim/init.lua ]]; then
    echo -n "Backing up old lvim/config.lua"
    mv ~/.config/lvim/config.lua ~/.config/lvim/config.lua.bak
    errorCheck
fi
echo -n "Setting up lvim/config.lua"
cp .config/lvim/config.lua ~/.config/lvim/
errorCheck
#+end_src
** DoomEmacs config
*** Requirements
#+begin_src bash
sudo pacman -S git emacs ripgrep find fd --noconfirm
#+end_src

#+RESULTS:

*** Install
#+begin_src bash
git clone https://github.com/doomemacs/doomemacs ~/.emacs.d
git switch develop
~/.emacs.d/bin/doom install
#+end_src
*** Notes
**** Some optional dependencies can be found through ~doom doctor~ command
#+begin_src bash
~/.emacs.d/bin/doom doctor
#+end_src
 * Refer to [[https://docs.doomemacs.org/latest/][Doom Docs]] for more info
**** Personal config at ~.doom.d/~
Run ~doom sync~ for install config modules
#+begin_src bash
~/.emacs.d/bin/doom sync
#+end_src
*** Update config
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating .doom.d files..."
cp  ~/.doom.d/* .doom.d/
errorCheck
#+end_src
*** Setup config
#+begin_src bash :tangle dotconfig.sh
if [[ -d ~/.doom.d/ ]]; then
    echo -n "Backing up old doom emacs files..."
    mv ~/.doom.d ~/.doom.d.bak
    errorCheck
fi
echo -n "Setting up doom files"
cp  .doom.d/* ~/.doom.d/
errorCheck
#+end_src
** VSCodium config
*** Requirements
*** Install
#+begin_src bash
yay -S vscodium-bin
#+end_src
*** Notes
**** Packages list in ~packages-list/vscodium-package-list.txt~
#+begin_src bash
# generate list with command below
vscodium --list-extensions > vscoidum-packages-list.txt
#+end_src
**** Install packages
#+begin_src bash
cat vscodium-packages-list.txt | xargs -L1 vscodium --install-extension
#+end_src
*** Update config
#+begin_src bash :tangle dotupdate.sh
echo -n "Updating vscodium keybindings file..."
cp  ~/.config/VSCodium/User/keybindings.json .config/VSCodium/User/
errorCheck
echo -n "Updating vscodium settings file..."
cp  ~/.config/VSCodium/User/settings.json .config/VSCodium/User/
errorCheck
#+end_src
*** Setup config
#+begin_src bash :tangle dotconfig.sh
echo "Installing vscodium extensions..."
cat packages-list/vscodium-packages-list.txt | xargs -L1 codium --install-extension
echo "Installing vscodium extensions... Completed"
if [[ -d ~/.config/VSCodium/User ]]; then
    echo -n "Backing old codium files"
    mv ~/.config/VSCodium/User/keybindings.json ~/.config/VSCodium/User/keybindings.json.bak
    errorCheck
    mv ~/.config/VSCodium/User/settings.json ~/.config/VSCodium/User/settings.json.bak
    errorCheck
fi
echo "Moving codium files..."
cp .config/VSCodium/User/keybindings.json ~/.config/VSCodium/User/keybindings.json
errorCheck
cp .config/VSCodium/User/settings.json ~/.config/VSCodium/User/settings.json
errorCheck
#+end_src
** Kwrite
Managed through KDE config : [[*KDE-Config][KDE-Config]]
*** Install
#+begin_src bash
sudo pacman -S kwrite --noconfirm
#+end_src
** Kate
Managed through KDE config : [[*KDE-Config][KDE-Config]]
*** Install
#+begin_src bash
sudo pacman -S kate --noconfirm
#+end_src
* Gesture config
Configuration for ~Gestures~ Application.
~Gestures~ application binds various keyboard shortcuts to touchpad gestures.
** Requirements
#+begin_src bash
sudo pacman -S xdotool --noconfirm
#+end_src
** Install ~Gestures~ application
#+BEGIN_SRC bash
sudo pacman -S community/gestures --noconfirm
#+END_SRC
** Configuration
Files stored as ~"~/.config/libinput-gestures.conf"~
Link to file: [[file:.config/libinput-gestures.conf][Gestures config file.]]
** Setup gestures
#+begin_src bash
cp .config/libinput-gestures.conf  ~/.config/libinput-gestures.conf
#+end_src
* Packages List ~packages-list/~
** Directory structure
#+begin_src bash :shebang /usr/bin/bash :results code :exports both
tree ./packages-list
#+end_src

#+RESULTS:
#+begin_src bash
./packages-list
├── brew-packages-list.txt
├── cargo-packages-list.txt
├── flatpak-packages-list.txt
├── go-packages-list.txt
├── npm-packages-list.txt
├── pacman-packages-list.txt
├── pip-packages-list.txt
├── script.sh
├── vscodium-packages-list.txt
└── yay-packages-list.txt

0 directories, 10 files
#+end_src
** script.sh
Script to generate packages list for all package managers
[[file:packages-list/script.sh][Pacakge list generator script]]
** Pacman packages
Pacman: Package installer for Arch Linux
*** List generated
1. Explicitly installed packages
   Created with command:
#+BEGIN_SRC bash
pacman -Qqe > pacman-packages-list.txt
#+END_SRC
2. All packages
   Created with command:
#+BEGIN_SRC bash
pacman -Qq > pacman-packages-list-full.txt
#+END_SRC
3. Pacman option to remember for list generation:
   |--------+-----------------------------------------|
   | Option | Action                                  |
   |--------+-----------------------------------------|
   | -Q     | List all packages with version          |
   | -q     | List all packages without version       |
   | -e     | List all explicitly installed packages  |
   | -n     | List packages omitting foreign packages |
   | -m     | List all foreign packages               |
   |--------+-----------------------------------------|
4. Examples
#+BEGIN_SRC bash
pacman -Qqen
#+END_SRC
5. Link for reference: [[https://wiki.archlinux.org/title/pacman/Tips_and_tricks#List_of_installed_packages][Pacman/Tips and tricks - ArchWiki]]
** Yay packages
#+begin_src bash
yay -Qm > yay-packages-list.txt
#+end_src
** Brew packages
#+begin_src bash
brew list > brew-packages-list.txt
#+end_src
** Flatpak packages
#+begin_src bash
flatpak list > flatpak-packages-list.txt
#+end_src
** Pip global packages
Pip: Package install for python
#+BEGIN_SRC bash
pip freeze | awk '{print $1}' > pip-packages-list.txt
#+END_SRC
** Npm global packages
Npm: Node package manager
 #+BEGIN_SRC bash
 npm -g list | awk '{print $2}' | awk -F '@' '{print $1}' > npm-packages-list.txt
 #+END_SRC
** Go global packages
#+begin_src bash
go list ... > go-packages-list.txt
#+end_src
** Rust global packages
#+begin_src bash
cargo install --list > rust-packages-list.txt
#+end_src
* Manuals
#+begin_src bash :shebang /usr/bin/bash :results code :exports both
tree ./manuals
#+end_src

#+RESULTS:
#+begin_src bash
./manuals
├── emacs-manual.org
├── linux-admin.md
├── linux-admin.org
└── vue-nuxt-guide.org

0 directories, 4 files
#+end_src

* Install-Script
** Directory structure
#+begin_src bash :shebang /usr/bin/bash :results code :exports both
tree ./install-script
#+end_src

#+RESULTS:
#+begin_src bash
./install-script
├── install-script.md
├── install-script.org
├── install-script.pdf
└── install-script.sh

0 directories, 4 files
#+end_src
* Script.sh
Script to run on KDE ~cmd~ widget: [[file:script.sh][Script]]
Link to file: [[file:script.sh][script.sh]]
* Exports
** KDE-Shortcuts
[[file:exports/ani-kde-scheme.kksrc][Global configuration file for KDE]]
** KDE-Config
*** Requirements
#+begin_src bash :tangle dotconfig.sh
pip install konsave
#+end_src
*** File: [[file:exports/ani-kde-config.knsv][Konsave configuration file]]
Generated by command
#+begin_src bash
konsave -s ani-kde-config
konsave -e ani-kde-config
#+end_src
*** Setup
#+begin_src bash :tangle dotconfig.sh
echo "Installing KDE Config"
if [[ -e ~/ani-kde-config.knsv ]]; then
    echo -n "Backing up old kde config files..."
    mv ~/ani-kde-config.knsv ~/ani-kde-config.knsv.bak
    errorCheck
fi
echo -n "Moving kde config files..."
cp ./exports/ani-kde-config.knsv ~/ani-kde-config.knsv
errorCheck
echo -n "Applying kde config files..."
konsave -i ~/ani-kde-config.knsv
errorCheck
#+end_src
*** Documentation: [[https://github.com/Prayag2/konsave][Konsave | Github]]
** KDE-Tiling
- ~Krohnkite~: Kwin script to emulate tiling window manager.
- Documentation: [[https://github.com/esjeon/krohnkite][Krohnkite | Github]]
